### ISSUE TITLE
Getting error using the API, worked fine couple of days ago.

### ISSUE THREAD

**Issue by erensevin** [martin-majlis/Wikipedia-API#60]
Whenever i try to use the API i now get error JSONDecodeError: Expecting value.

Example when using page_py.exists()

```py
page_py
Out[4]: Python_(programming_language) (id: ??, ns: 0)

page_py.exists()
Traceback (most recent call last):

  File "C:\Users\Eren\anaconda3\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)

  File "C:\Users\Eren\anaconda3\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)

  File "C:\Users\Eren\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "C:\Users\Eren\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None

JSONDecodeError: Expecting value


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\Eren\AppData\Local\Temp\ipykernel_26872\3834438054.py", line 1, in <module>
    page_py.exists()

  File "C:\Users\Eren\anaconda3\lib\site-packages\wikipediaapi\__init__.py", line 875, in exists
    return bool(self.pageid != -1)

  File "C:\Users\Eren\anaconda3\lib\site-packages\wikipediaapi\__init__.py", line 839, in __getattr__
    self._fetch(call)

  File "C:\Users\Eren\anaconda3\lib\site-packages\wikipediaapi\__init__.py", line 1029, in _fetch
    getattr(self.wiki, call)(self)

  File "C:\Users\Eren\anaconda3\lib\site-packages\wikipediaapi\__init__.py", line 297, in info
    raw = self._query(page, params)

  File "C:\Users\Eren\anaconda3\lib\site-packages\wikipediaapi\__init__.py", line 494, in _query
    return r.json()

  File "C:\Users\Eren\anaconda3\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)

JSONDecodeError: Expecting value

**Comment by erensevin** [comment]
Works again now, server issue yesterday maybe?

**Comment by erensevin** [comment]
Works again now, server issue yesterday maybe?

**Comment by neurochilds** [comment]
I'm currently having the same issue. Worked fine for me the last few weeks, but now getting: 

`requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`
